# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 18:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20160107_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='username',
            field=models.CharField(default=datetime.datetime(2016, 3, 18, 18, 30, 21, 422993, tzinfo=utc), max_length=30),
            preserve_default=False,
        ),
    ]
